import { LineChart, Sparkles } from 'lucide-react'
import type { Development, DevelopmentHistoryItem, Skill, Trait } from '../types'
import { formatSimTime, pct, labelize } from '../lib/format'
import { EmptyState, Panel, ProgressBar } from '../components/Ui'

export function Development({ current, history, traits, skills }: { current: Development | null; history: DevelopmentHistoryItem[]; traits: Trait[]; skills: Skill[] }) {
  const areas = [
    ['physicalScore', 'Fisico'], ['cognitiveScore', 'Cognitivo'], ['socialScore', 'Sociale'], ['emotionalScore', 'Emotivo'], ['educationScore', 'Istruzione'],
  ] as const
  return <div className="split-grid"><Panel title="Stato dello sviluppo" eyebrow="CRESCITA NEL TEMPO"><div className="dev-grid">{areas.map(([key, label]) => <div className="dev-card" key={key}><span>{label}</span><strong>{pct(Number(current?.[key] ?? 0))}</strong><ProgressBar value={Number(current?.[key] ?? 0)} compact /></div>)}</div></Panel><Panel title="Profilo dei tratti" eyebrow="PERSONALITÀ" right={<span className="tiny-muted">I tratti cambiano con l'esperienza</span>}><div className="score-stack">{traits.map((t) => <div key={t.code} className="trait-card"><Sparkles size={14} /><div><strong>{labelize(t.name)}</strong><ProgressBar value={t.value} compact /></div><span>{pct(t.value)}</span></div>)}</div></Panel><Panel title="Competenze" eyebrow="CAPACITÀ APPRESE" right={<span className="tiny-muted">{skills.length} skill</span>}><div className="score-stack">{skills.length ? skills.map((skill) => <div key={skill.code} className="trait-card"><Sparkles size={14} /><div><strong>{labelize(skill.name)}</strong><ProgressBar value={Number(skill.proficiency ?? 0)} compact /></div><span>{pct(Number(skill.proficiency ?? 0))}</span></div>) : <EmptyState title="Nessuna skill" text="Le competenze appariranno quando Asami inizierà ad apprendere e praticare." />}</div></Panel><Panel title="Cronologia" eyebrow="REGISTRO DELLO SVILUPPO"><div className="history-list">{history.length ? history.slice(0, 40).map((h, i) => <div className="history-row" key={`${h.updatedSimulationAt}-${i}`}><div className="history-point"><LineChart size={13} /></div><div><strong>{h.updatedSimulationAt ? formatSimTime(h.updatedSimulationAt) : '—'}</strong><span>Fisico {pct(Number(h.physicalScore ?? 0))} · Cognitivo {pct(Number(h.cognitiveScore ?? 0))} · Sociale {pct(Number(h.socialScore ?? 0))}</span></div></div>) : <EmptyState title="Nessuna cronologia di sviluppo" text="Le istantanee dello sviluppo appariranno con l'avanzare del tempo simulato." />}</div></Panel></div>
}
