import { Brain, HeartPulse, MapPin, Sparkles, Target, Zap } from 'lucide-react'
import type { Dashboard, Simulation } from '../types'
import { formatSimTime, formatValue, labelize, pct } from '../lib/format'
import { EmptyState, Panel, ProgressBar, Score, StatusPill } from '../components/Ui'

export function Overview({ simulation, dashboard }: { simulation: Simulation; dashboard: Dashboard }) {
  const topNeed = [...dashboard.needs].sort((a, b) => Number(b.value) - Number(a.value))[0]
  const topEmotion = dashboard.emotions[0]
  const topGoal = [...dashboard.goals].sort((a, b) => Number(b.priority) - Number(a.priority))[0]
  const action = dashboard.currentAction
  const strongestTraits = [...dashboard.traits].sort((a, b) => Number(b.value) - Number(a.value)).slice(0, 5)
  const loc = dashboard.location

  return <>
    <div className="hero-card">
      <div className="hero-orb"><Sparkles size={32} /></div>
      <div className="hero-copy"><div className="eyebrow">AUTONOMOUS ENTITY · PERSON</div><h2>{dashboard.entity.displayName}</h2><p>{dashboard.entity.description || 'Autonomous simulated person.'}</p><div className="hero-meta"><StatusPill value={dashboard.entity.status} /><span>Simulation time · {formatSimTime(simulation.currentSimulationAt)}</span></div></div>
      <div className="hero-action"><div className="eyebrow">NOW</div><strong>{action ? labelize(action.actionType) : 'Observing'}</strong><span>{action?.status ? labelize(action.status) : 'Waiting for next engine tick'}</span></div>
    </div>

    <div className="metric-grid">
      <div className="metric-card"><div className="metric-icon"><HeartPulse size={18} /></div><div><span>Need dominante</span><strong>{topNeed ? labelize(topNeed.name) : '—'}</strong><small>{topNeed ? `${pct(topNeed.value)} pressure` : 'No data'}</small></div></div>
      <div className="metric-card"><div className="metric-icon"><Brain size={18} /></div><div><span>Emozione dominante</span><strong>{topEmotion ? labelize(topEmotion.name) : '—'}</strong><small>{topEmotion ? pct(topEmotion.intensity) : 'No data'}</small></div></div>
      <div className="metric-card"><div className="metric-icon"><Target size={18} /></div><div><span>Intenzione / goal</span><strong>{topGoal?.title || 'Nessun goal attivo'}</strong><small>{topGoal ? `${pct(topGoal.progress)} progress · P${topGoal.priority}` : 'The engine will create one'}</small></div></div>
      <div className="metric-card"><div className="metric-icon"><Zap size={18} /></div><div><span>Clock speed</span><strong>× realtime</strong><small>{simulation.status} · v{simulation.version}</small></div></div>
    </div>

    <div className="overview-grid">
      <Panel title="Needs pressure" eyebrow="INTERNAL STATE">
        <div className="list-stack">{dashboard.needs.map((n) => <ProgressBar key={n.code} value={n.value} label={n.name} />)}</div>
      </Panel>
      <Panel title="Emotional field" eyebrow="EMOTIONS">
        <div className="emotion-grid">{dashboard.emotions.map((e) => <div className="emotion-tile" key={e.code}><div className="emotion-top"><span>{labelize(e.name)}</span><strong>{pct(e.intensity)}</strong></div><ProgressBar value={e.intensity} compact /></div>)}</div>
      </Panel>
      <Panel title="Personality trajectory" eyebrow="DEVELOPMENT SIGNALS" right={<span className="tiny-muted">Current traits</span>}>
        <div className="score-stack">{strongestTraits.map((t) => <Score key={t.code} label={t.name} value={t.value} />)}</div>
      </Panel>
      <Panel title="Where / what" eyebrow="WORLD STATE">
        {loc ? <div className="location-card"><div className="location-icon"><MapPin size={18} /></div><div><strong>{labelize(loc.locationType)}</strong><span>{loc.addressData ? formatValue(loc.addressData) : 'Location linked to entity'}</span><small>Since {formatSimTime(loc.sinceSimulationAt)}</small></div></div> : <EmptyState icon={<MapPin size={20} />} title="No location yet" text="The current schema has no location for Asami." />}
      </Panel>
    </div>

    <Panel title="Goals" eyebrow="INTENTIONS">
      {dashboard.goals.length ? <div className="goal-table">{dashboard.goals.map((g) => <div className="goal-row" key={g.id}><div><strong>{g.title}</strong><span>{g.description || formatValue(g.motivation) || labelize(g.goalType)}</span></div><div className="goal-progress"><ProgressBar value={g.progress} compact /><small>{pct(g.progress)}</small></div><StatusPill value={g.status} /></div>)}</div> : <EmptyState icon={<Target size={20} />} title="No goals" text="Goals are generated by the autonomy engine from current needs." />}
    </Panel>
  </>
}
