const test=require("node:test");
const assert=require("node:assert/strict");
const { needPriorityState, scoreAction }=require("../src/services/decision-rules");
const { computeLearningStrength }=require("../src/services/experience-learning-service");
const { memoryRelevance }=require("../src/services/memory-service");
const { traitBehaviorWeights }=require("../src/services/state-service");
const { getInterruptionReason, isCriticalNeed }=require("../src/simulation/engine");

test("need priority exposes CRITICAL/HIGH/MEDIUM/LOW hierarchy",()=>{assert.equal(needPriorityState([{code:"THIRST",value:.91,priorityWeight:1}]).level,"CRITICAL");assert.equal(needPriorityState([{code:"HUNGER",value:.67,priorityWeight:1}]).level,"HIGH");assert.equal(needPriorityState([{code:"FUN",value:.4,priorityWeight:1}]).level,"MEDIUM");assert.equal(needPriorityState([{code:"FUN",value:.2,priorityWeight:1}]).level,"LOW");});
test("critical need gets an explicit decision advantage",()=>{const needs=[{code:"THIRST",value:.95,priorityWeight:1},{code:"SOCIAL_NEED",value:.9,priorityWeight:1}];assert.ok(scoreAction("DRINKING",needs,[],{localResources:{water:1}})>scoreAction("TALKING",needs,[]));});
test("a single failure has weaker learning than repeated contextual failures",()=>{const first=Math.abs(computeLearningStrength({outcome:"FAILURE",confidence:.96,repetition:.125,contextSimilarity:.35}));const repeated=Math.abs(computeLearningStrength({outcome:"FAILURE",confidence:.96,repetition:1,contextSimilarity:1}));assert.ok(first>0);assert.ok(repeated>first*3);assert.ok(repeated<=.25);});
test("success and failure both produce bounded learning signals",()=>{const success=computeLearningStrength({outcome:"SUCCESS",confidence:.8,repetition:.5,contextSimilarity:.8});const failure=computeLearningStrength({outcome:"FAILURE",confidence:.8,repetition:.5,contextSimilarity:.8});assert.ok(success>0);assert.ok(failure<0);assert.ok(Math.abs(success)<.25);assert.ok(Math.abs(failure)<.25);});
test("memory relevance prefers goal/location/action matches over an unrelated recent memory",()=>{const context={simulationTime:"2026-09-22T10:00:00.000Z",goalIds:["goal-1"],locationId:"loc-1",locationType:"CAFE",candidateActionTypes:["TALKING"],targetEntityId:"person-1"};const relevant={simulationAt:"2026-09-21T10:00:00.000Z",importance:.6,strength:.7,confidence:.9,locationId:"loc-1",metadata:{goalId:"goal-1",actionType:"TALKING",location:{type:"CAFE",id:"loc-1"},targetEntityId:"person-1"},content:"Talking with person-1 at the cafe advanced my social goal."};const unrelated={simulationAt:"2026-09-22T09:30:00.000Z",importance:.5,strength:.7,confidence:.9,locationId:"loc-9",metadata:{actionType:"WATCHING",location:{type:"HOME",id:"loc-9"}},content:"I watched something at home."};assert.ok(memoryRelevance(relevant,context)>memoryRelevance(unrelated,context));});
test("trait mapping is evidence metadata, not a direct action-to-trait update",()=>{assert.equal(traitBehaviorWeights("TALKING").EXTRAVERSION,.6);assert.equal(traitBehaviorWeights("TALKING").SOCIABILITY,.7);assert.equal(traitBehaviorWeights("TALKING").EMPATHY,.25);});
test("long actions are interrupted by incompatible critical needs",()=>{const result=getInterruptionReason("WORKING",[{code:"THIRST",value:.91},{code:"SLEEPINESS",value:.2}],{recentEvents:[]});assert.equal(result.type,"CRITICAL_NEED");assert.equal(result.code,"THIRST");});
test("walking toward a resource is not interrupted by the same critical need",()=>{assert.equal(getInterruptionReason("WALKING",[{code:"THIRST",value:.95},{code:"SLEEPINESS",value:.2}],{recentEvents:[]}),null);assert.equal(getInterruptionReason("WALKING",[{code:"HUNGER",value:.95},{code:"SLEEPINESS",value:.2}],{recentEvents:[]}),null);});
test("sleeping is not interrupted by sleepiness itself",()=>{const result=getInterruptionReason("SLEEPING",[{code:"SLEEPINESS",value:.95},{code:"THIRST",value:.2}],{recentEvents:[]});assert.equal(result,null);});
test("energy and safety are critical only when low",()=>{assert.equal(isCriticalNeed("ENERGY",.9),false);assert.equal(isCriticalNeed("ENERGY",.14),true);assert.equal(isCriticalNeed("SAFETY",1),false);assert.equal(isCriticalNeed("SAFETY",.19),true);});
test("healthy energy and safety never interrupt long actions",()=>{assert.equal(getInterruptionReason("SLEEPING",[{code:"ENERGY",value:.9},{code:"SAFETY",value:1}],{recentEvents:[]}),null);assert.equal(getInterruptionReason("STUDYING",[{code:"ENERGY",value:.9},{code:"SAFETY",value:1}],{recentEvents:[]}),null);});
