const ACTIONS = [
  "SLEEPING","EATING","DRINKING","TALKING","PLAYING","RESTING",
  "STUDYING","READING","EXPLORING","WALKING","WORKING","WATCHING"
];

const actionNeeds={EATING:{HUNGER:2.4},DRINKING:{THIRST:2.8},TALKING:{SOCIAL_NEED:1.15,BELONGING:.75},PLAYING:{FUN:1.6},STUDYING:{ACHIEVEMENT:.9,CURIOSITY:.5},READING:{CURIOSITY:.8,ACHIEVEMENT:.3},EXPLORING:{CURIOSITY:1.4},WALKING:{FUN:.3,CURIOSITY:.3},WORKING:{ACHIEVEMENT:1},WATCHING:{FUN:.9}};
const actionNeedGates={EATING:["HUNGER",.15],DRINKING:["THIRST",.25],TALKING:["SOCIAL_NEED",.22],PLAYING:["FUN",.18],STUDYING:["ACHIEVEMENT",.18],READING:["CURIOSITY",.18],EXPLORING:["CURIOSITY",.18],WORKING:["ACHIEVEMENT",.2]};
const CRITICAL_NEED_ACTIONS={THIRST:{action:"DRINKING",threshold:.8,maxBoost:1.6,resource:"water",direction:"HIGH"},HUNGER:{action:"EATING",threshold:.8,maxBoost:1.4,resource:"food",direction:"HIGH"},SLEEPINESS:{action:"SLEEPING",threshold:.85,maxBoost:1.5,direction:"HIGH"},ENERGY:{action:"SLEEPING",threshold:.15,maxBoost:1.5,direction:"LOW"},SAFETY:{action:"RESTING",threshold:.2,maxBoost:1.5,direction:"LOW"}};
const RESOURCE_REQUIREMENTS={EATING:{resource:"food",amount:1},DRINKING:{resource:"water",amount:1}};
const NEED_PRIORITY_THRESHOLDS={CRITICAL:{pressure:.8,safetyMax:.2,energyMax:.15},HIGH:{pressure:.6,safetyMax:.4,energyMax:.3},MEDIUM:{pressure:.35,safetyMax:.6,energyMax:.5}};
const ACTION_TRAIT_PROFILES={TALKING:{EXTRAVERSION:1.20,SOCIABILITY:1.35,EMPATHY:.35,CONFIDENCE:.25,AGREEABLENESS:.30,INDEPENDENCE:-.40,NEUROTICISM:-.15},EXPLORING:{OPENNESS:1.20,CURIOSITY:1.30,RISK_TAKING:.90,CONFIDENCE:.35,INDEPENDENCE:.45,IMPULSIVITY:.25,NEUROTICISM:-.30},STUDYING:{CONSCIENTIOUSNESS:1.25,DISCIPLINE:1.35,CURIOSITY:.70,PATIENCE:.55,CONFIDENCE:.15,IMPULSIVITY:-.50},READING:{OPENNESS:.75,CURIOSITY:1.25,PATIENCE:.60,CONSCIENTIOUSNESS:.40,DISCIPLINE:.35,IMPULSIVITY:-.25},WORKING:{CONSCIENTIOUSNESS:1.30,DISCIPLINE:1.25,PATIENCE:.55,CONFIDENCE:.25,INDEPENDENCE:.30,IMPULSIVITY:-.40},PLAYING:{OPENNESS:.55,EXTRAVERSION:.45,IMPULSIVITY:.80,CONFIDENCE:.25,RISK_TAKING:.35,CONSCIENTIOUSNESS:-.15},WALKING:{OPENNESS:.25,INDEPENDENCE:.45,CONFIDENCE:.20,RISK_TAKING:.20,PATIENCE:.15},SLEEPING:{PATIENCE:.45,DISCIPLINE:.35,NEUROTICISM:.15,IMPULSIVITY:-.25},RESTING:{PATIENCE:.55,NEUROTICISM:.25,CONSCIENTIOUSNESS:-.10,IMPULSIVITY:-.20},WATCHING:{PATIENCE:.40,OPENNESS:.20,NEUROTICISM:.15,EXTRAVERSION:-.15},EATING:{PATIENCE:.10,IMPULSIVITY:-.05},DRINKING:{PATIENCE:.08,IMPULSIVITY:-.08}};
function needValue(needs,code){const need=(needs||[]).find(item=>item.code===code);return need?Number(need.value):0;}
function needWeight(needs,code){const need=(needs||[]).find(item=>item.code===code);return Number(need?.priorityWeight||1);}
function normalizeNeedCode(code){return String(code||"").trim().toUpperCase();}
function isNeedCritical(code,value,threshold){const direction=CRITICAL_NEED_ACTIONS[normalizeNeedCode(code)]?.direction;if(direction==="HIGH")return value>=threshold;if(direction==="LOW")return value<=threshold;return false;}
function needPriorityState(needs=[]){const pressureCodes=["HUNGER","THIRST","SLEEPINESS","SOCIAL_NEED","FUN","CURIOSITY","ACHIEVEMENT","BELONGING"];let highest=null;for(const need of needs){const code=normalizeNeedCode(need.code),value=Number(need.value||0),weight=Math.max(.1,Number(need.priorityWeight||1));let level="LOW";if(code==="SAFETY")level=value<=NEED_PRIORITY_THRESHOLDS.CRITICAL.safetyMax?"CRITICAL":value<=NEED_PRIORITY_THRESHOLDS.HIGH.safetyMax?"HIGH":value<=NEED_PRIORITY_THRESHOLDS.MEDIUM.safetyMax?"MEDIUM":"LOW";else if(code==="ENERGY")level=value<=NEED_PRIORITY_THRESHOLDS.CRITICAL.energyMax?"CRITICAL":value<=NEED_PRIORITY_THRESHOLDS.HIGH.energyMax?"HIGH":value<=NEED_PRIORITY_THRESHOLDS.MEDIUM.energyMax?"MEDIUM":"LOW";else if(pressureCodes.includes(code))level=value>=NEED_PRIORITY_THRESHOLDS.CRITICAL.pressure?"CRITICAL":value>=NEED_PRIORITY_THRESHOLDS.HIGH.pressure?"HIGH":value>=NEED_PRIORITY_THRESHOLDS.MEDIUM.pressure?"MEDIUM":"LOW";const rank={LOW:0,MEDIUM:1,HIGH:2,CRITICAL:3}[level],urgency=level==="CRITICAL"?1+value*.25:level==="HIGH"?.65+value*.2:level==="MEDIUM"?.3+value*.15:value*.1,item={code,value,weight,level,rank,urgency:Math.min(1.5,urgency*weight)};if(!highest||item.rank>highest.rank||(item.rank===highest.rank&&item.urgency>highest.urgency))highest=item;}return highest||{code:null,value:0,weight:1,level:"LOW",rank:0,urgency:0};}
function actionNeedCodes(action){const direct=Object.keys(actionNeeds[action]||{});if(action==="SLEEPING")return["SLEEPINESS","ENERGY"];if(action==="RESTING")return["ENERGY","COMFORT"];return direct;}
function actionPriorityState(action,needs=[]){const priority=needPriorityState(needs),codes=new Set(actionNeedCodes(action).map(normalizeNeedCode)),directlyServes=codes.has(priority.code),criticalAlternative=priority.level==="CRITICAL"&&((priority.code==="THIRST"||priority.code==="HUNGER")&&action==="WALKING");if(priority.level==="CRITICAL")return{...priority,servesPriorityNeed:directlyServes||criticalAlternative,multiplier:directlyServes?2.4:criticalAlternative?1.45:1};if(priority.level==="HIGH")return{...priority,servesPriorityNeed:directlyServes,multiplier:directlyServes?1.55:.9};if(priority.level==="MEDIUM")return{...priority,servesPriorityNeed:directlyServes,multiplier:directlyServes?1.2:1};return{...priority,servesPriorityNeed:directlyServes,multiplier:1};}
function resourceModifier(action,resourceContext={}){const requirement=RESOURCE_REQUIREMENTS[action];if(!requirement)return 0;const localResources=resourceContext.localResources||{},available=Number(localResources[requirement.resource]??0),localBlocked=Boolean(resourceContext.blockedResources?.[requirement.resource]);if(available>=requirement.amount)return localBlocked?-.2:.08;const nearest=resourceContext.nearestResources?.[requirement.resource];if(!nearest)return-1.25;const travelMinutes=Number(nearest.travelMinutes),finiteTravel=Number.isFinite(travelMinutes)?travelMinutes:60,travelPenalty=Math.min(.55,Math.max(.05,finiteTravel/60*.45)),knowledgePenalty=localBlocked?.35:0;return-.55-travelPenalty-knowledgePenalty;}
function criticalNeedModifier(action,needs,resourceContext={}){for(const[code,policy]of Object.entries(CRITICAL_NEED_ACTIONS)){if(policy.action!==action)continue;const value=needValue(needs,code);if(!isNeedCritical(code,value,policy.threshold))continue;if(policy.resource){const required=RESOURCE_REQUIREMENTS[action],available=Number(resourceContext.localResources?.[policy.resource]??0);if(!required||available<required.amount)return 0;}const urgency=policy.direction==="HIGH"?Math.min(1,(value-policy.threshold)/(1-policy.threshold)):Math.min(1,(policy.threshold-value)/policy.threshold);return urgency*policy.maxBoost*needWeight(needs,code);}return 0;}
function personalityActionBias(action,traits=[]){const profile=ACTION_TRAIT_PROFILES[action];if(!profile||!Array.isArray(traits)||!traits.length)return 0;const values=new Map(traits.map(item=>[String(item.code||"").trim().toUpperCase(),Number(item.value)]));let weighted=0,totalWeight=0;for(const[code,weight]of Object.entries(profile)){const value=values.get(code);if(!Number.isFinite(value))continue;weighted+=(value-.5)*weight;totalWeight+=Math.abs(weight);}if(!totalWeight)return 0;return Math.max(-1.25,Math.min(1.25,(weighted/totalWeight)*2.7));}
function sleepReadiness(needs){const sleepiness=needValue(needs,"SLEEPINESS"),energy=needValue(needs,"ENERGY"),thirst=needValue(needs,"THIRST"),hunger=needValue(needs,"HUNGER");if(sleepiness<.25&&energy>.45)return 0;let modifier=1;if(sleepiness<.40)modifier*=.30;else if(sleepiness<.55)modifier*=.65;if(thirst>.55)modifier*=Math.max(.12,1-(thirst-.55)*2.4);if(hunger>.60)modifier*=Math.max(.18,1-(hunger-.60)*1.8);if(energy>.82&&sleepiness<.58)modifier*=.35;return Math.max(0,modifier);}
function activityDiversityBonus(action,recentActions=[]){
  const eligible=new Set(["TALKING","PLAYING","STUDYING","READING","EXPLORING","WORKING"]);
  const normalized=String(action||"").toUpperCase();
  if(!eligible.has(normalized)||!Array.isArray(recentActions))return 0;
  const count=recentActions.map(normalizeNeedCode).filter(item=>item===normalized).length;
  if(count===0)return .24;
  if(count===1)return .13;
  if(count===2)return .06;
  return 0;
}
function scoreAction(action,needs,traits,resourceContext={}){const gate=actionNeedGates[action],gatedNeed=gate?needValue(needs,gate[0]):null;if(gate&&gatedNeed<gate[1])return 0;const priority=actionPriorityState(action,needs);let score=0;if(action==="SLEEPING"){const sleepiness=needValue(needs,"SLEEPINESS"),energy=needValue(needs,"ENERGY"),readiness=sleepReadiness(needs);score+=Math.pow(Math.max(0,(sleepiness-.20))/0.80,1.35)*2.7*needWeight(needs,"SLEEPINESS");score+=Math.pow(Math.max(0,1-energy),1.10)*1.2*needWeight(needs,"ENERGY");score*=readiness;}else if(action==="RESTING"){const energy=needValue(needs,"ENERGY"),comfort=needValue(needs,"COMFORT");if(energy>=.72&&comfort<.65)score=0;else{score+=Math.max(0,1-energy)*needWeight(needs,"ENERGY");score+=Math.max(0,.65-comfort)*.7*needWeight(needs,"COMFORT");if(energy>=.82)score*=.25;else if(energy>=.72)score*=.5;}}else{for(const[code,weight]of Object.entries(actionNeeds[action]||{}))score+=needValue(needs,code)*weight*needWeight(needs,code);}score*=priority.multiplier;score+=personalityActionBias(action,traits);score+=criticalNeedModifier(action,needs,resourceContext);return Math.max(0,score+resourceModifier(action,resourceContext));}
module.exports={ACTIONS,scoreAction,RESOURCE_REQUIREMENTS,criticalNeedModifier,needPriorityState,actionPriorityState,isNeedCritical,CRITICAL_NEED_ACTIONS,personalityActionBias,ACTION_TRAIT_PROFILES,sleepReadiness,activityDiversityBonus};
